spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=app_user
spring.datasource.password=app_password
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.h2.console.enabled=false
spring.jpa.open-in-view=false
