ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER app_user IDENTIFIED BY app_password;

GRANT CREATE SESSION TO app_user;
GRANT CREATE TABLE TO app_user;
GRANT CREATE SEQUENCE TO app_user;
GRANT CREATE VIEW TO app_user;
GRANT CREATE INDEX TO app_user;

ALTER USER app_user QUOTA UNLIMITED ON USERS;
